# Generated by Django 5.0.1 on 2024-01-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_brand_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_brand',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='products.product_manufacturer'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
