# Generated by Django 5.0.1 on 2024-01-02 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Payments',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=36, null=True)),
                ('client_order_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('client_payment_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('client_payment_signature', models.CharField(blank=True, max_length=1024, null=True)),
                ('for_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='user_profile.orders')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
